name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Run Tests
      run: |
        cd tests/
        make
        ./test
        exit_code=$?
        if [ $exit_code -gt 0 ]; then
          echo "Tests failed with exit code: $exit_code"
          exit 1
        fi
    - name: Update Pull Request Status
      uses: peter-evans/create-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Test Results:
          Status: ${{ steps.RunTests.outputs.status }}
