name: Run invalidpostest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bishopmovestest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test for Invalid Positions
      run: |
        make
        cd tests/
        make invalidpostest
        ./invalidpostest
        exit_code=$?
        if [ $exit_code -gt 0 ]; then
          echo "Invalid position test failed with exit code: $exit_code"
          exit 1
        fi
