name: Run pawnpromotiontest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pawnpromotiontest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: |
        make
        cd tests/
        make pawnpromotiontest
        ./pawnpromotiontest
        exit_code=$?
        if [ $exit_code -gt 0 ]; then
          echo "Pawn promotion test failed with exit code: $exit_code"
          exit 1
        fi
