name: Run rookmovestest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rookmovestest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: |
        make
        cd tests/
        make rookmovestest
        ./rookmovestest
        exit_code=$?
        if [ $exit_code -gt 0 ]; then
          echo "Rook movement test failed with exit code: $exit_code"
          exit 1
        fi
