name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: |
        make
        cd tests/
        make
        ./test
        exit_code=$?
        if [ $exit_code -gt 0 ]; then
          echo "Tests failed with exit code: $exit_code"
          exit 1
        fi
